AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI Pronunciation Trainer - Serverless Speech Evaluation API

Globals:
    Function:
        Timeout: 30
        MemorySize: 1024
        Runtime: python3.12
        Environment:
            Variables:
                USE_API_ASR: true

Parameters:
    WhisperApiKey:
        Type: String
        NoEcho: true
        Description: Your OpenAI API key (get it at https://platform.openai.com/api-keys)

Resources:
    # API Gateway
    PronunciationTrainerApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            Cors:
                AllowMethods: "'GET,POST,OPTIONS'"
                AllowHeaders: "'*'"
                AllowOrigin: "'*'"
                AllowCredentials: true
            GatewayResponses:
                DEFAULT_4XX:
                    ResponseParameters:
                        Headers:
                            Access-Control-Allow-Origin: "'*'"
                            Access-Control-Allow-Headers: "'*'"
                DEFAULT_5XX:
                    ResponseParameters:
                        Headers:
                            Access-Control-Allow-Origin: "'*'"
                            Access-Control-Allow-Headers: "'*'"

    # Main Lambda Function - Speech to Score
    SpeechToScoreFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: .
            Handler: lambdaSpeechToScore.lambda_handler
            Description: Evaluates pronunciation accuracy from recorded audio using OpenAI Whisper API
            Layers:
                - !Sub 'arn:aws:lambda:${AWS::Region}:145266761615:layer:ffmpeg:4'
            Environment:
                Variables:
                    USE_API_ASR: true
                    WHISPER_API_KEY: !Ref WhisperApiKey
                    OPENAI_API_BASE: !Ref OpenaiApiBase
            Events:
                ApiEvent:
                    Type: Api
                    Properties:
                        RestApiId: !Ref PronunciationTrainerApi
                        Path: /GetAccuracyFromRecordedAudio
                        Method: POST
            Tags:
                Application: PronunciationTrainer
                Component: SpeechEvaluation

    # CloudWatch Log Group with retention
    SpeechToScoreFunctionLogGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: !Sub '/aws/lambda/${SpeechToScoreFunction}'
            RetentionInDays: 7

    # CloudWatch Alarms
    SpeechToScoreFunctionErrorAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Alert when Lambda function errors exceed threshold
            MetricName: Errors
            Namespace: AWS/Lambda
            Statistic: Sum
            Period: 300
            EvaluationPeriods: 1
            Threshold: 5
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: FunctionName
                  Value: !Ref SpeechToScoreFunction

    SpeechToScoreFunctionThrottleAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Alert when Lambda function is throttled
            MetricName: Throttles
            Namespace: AWS/Lambda
            Statistic: Sum
            Period: 300
            EvaluationPeriods: 1
            Threshold: 1
            ComparisonOperator: GreaterThanThreshold
            Dimensions:
                - Name: FunctionName
                  Value: !Ref SpeechToScoreFunction

Outputs:
    ApiUrl:
        Description: API Gateway endpoint URL for production stage
        Value: !Sub 'https://${PronunciationTrainerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/'
        Export:
            Name: !Sub '${AWS::StackName}-ApiUrl'

    SpeechToScoreFunctionArn:
        Description: ARN of the Speech to Score Lambda Function
        Value: !GetAtt SpeechToScoreFunction.Arn
        Export:
            Name: !Sub '${AWS::StackName}-SpeechToScoreFunctionArn'

    ApiId:
        Description: API Gateway ID
        Value: !Ref PronunciationTrainerApi
        Export:
            Name: !Sub '${AWS::StackName}-ApiId'
